modLoader="javafml" # mandatory
loaderVersion="[28,)"
license="All rights reserved"

[[mods]]
modId="iboren"
version="2.4" # Explicit version instead of ${file.jarVersion}
displayName="Iboren Mod"
authors="Feovee"
description='''A cool mod description'''
logoFile="iboren_mod_logo.png" # optional
credits="" # optional

[[dependencies.iboren]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.iboren]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3,1.16.5]"
ordering="NONE"
side="BOTH"

[[dependencies.iboren]]
modId="geckolib3"
mandatory=true
versionRange="[3.0.106,)"
ordering="BEFORE"
side="BOTH"
